### ISSUE TITLE
Hosting whirled

### ISSUE THREAD

**Issue by srachit** [greyhavens/whirled-sdk#1]
Hey Michael,
Now that three rings has dropped support of whirled, it has created problems for many people especially in games like kadesim which do not seem to work anymore, being a long term supporter and player of PP, I want to bring back kadesim. The original programmer has made the source code of it open, but it heavily relies on the whirled architecture. I was wondering if it'd be possible to make open source the server code for whirled so that we may host whirled and kadesim separately and continue to provide support for the PP community.

Thanks
Rachit Sengupta

**Comment by samskivert** [comment]
The Whirled code is completely open sourced in this repository: https://github.com/greyhavens/msoy

Whirled is a very complex system with many different moving parts, and I unfortunately don't have the time to document all of the different parts and how to configure them, so I'm afraid you're going to have to do a lot of investigating to figure out how everything fits together. I'm happy to try to answer specific questions you have about the process when I have the time, but I can't promise a great deal of support.
